[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/ar"
to = "/ar.html"
status = 200

[[redirects]]
from = "/ar/"
to = "/ar.html"
status = 200

[[redirects]]
from = "/fr"
to = "/fr.html"
status = 200

[[redirects]]
from = "/fr/"
to = "/fr.html"
status = 200

[[redirects]]
from = "/blog-post-2025-06-25"
to = "/blog-post-2025-06-25.html"
status = 200

[[redirects]]
from = "/blog-whatsapp-automation-smb"
to = "/blog-whatsapp-automation-smb.html"
status = 200

[[redirects]]
from = "/blog-cost-manual-whatsapp-management"
to = "/blog-cost-manual-whatsapp-management.html"
status = 200

[[redirects]]
from = "/blog-real-estate-whatsapp-automation"
to = "/blog-real-estate-whatsapp-automation.html"
status = 200

[[redirects]]
from = "/blog-whatsapp-lead-generation-sequences"
to = "/blog-whatsapp-lead-generation-sequences.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 